####################
# edit config file #
####################

# make sure the path are:
# 1. absolute paths
# 2. directories
####################################
project_name: 'bitmab2-metagenomes'
input_path: '/home/ad14556/BITMaB2-Metagenomes/project/11-jun-2020_bitmab2_metazoa_pipeline/00-test-data/'
output_path: '/home/ad14556/BITMaB2-Metagenomes/project/test/'
scratch_path: '/scratch/ad14556/functional_metagenomics/'


# quality control parameters
# look at the trimmomatic tutorial for more informations
####################################
adapters: '/home/ad14556/snakemake-pipelines/single-org-metagenomes/envs/Trimmomatic-0.39/adapters/NexteraPE-PE.fa'
phred_score: 'phred33'
mismatches: '2'
palindrome: '30'
simple_clip: '10'
leading_quality: '20'
trailing_quality: '20'
window_size: '4'
sliding_window_quality: '10'
minimum_seq_length: '25'