__default__:
    system: slurm #check if system is defined below
    account: hmb_lab #requred
    partition: bik_p #required
    time: 00-12:00:00 # minutes
    mem: 16 # GB
    threads: 1
    nodes: 1
    cpu: 1
    tasks: 1
    name: snakejob
    mail_user: 'ad14556@uga.edu'
    mail_type: 'FAIL'

run_rrap_mags:
    partition: iob_batch
    threads: 1
    mem: 16
    time: 00-012:00:00
    name: rrap

initial_fastqc:
    partition: iob_batch
    threads: 1
    mem: 10
    time: 00-01:00:00
    name: initial_fastqc

initial_multiqc:
    partition: iob_batch
    threads: 1
    mem: 10
    time: 00-01:00:00
    name: initial_multiqc

trimmomatic:
    partition: iob_batch
    threads: 32
    mem: 128
    time: 00-12:00:00
    name: trimmomatic

trimmed_fastqc:
    partition: iob_batch
    threads: 1
    mem: 10
    time: 00-01:00:00
    name: trimmed_fastqc

trimmed_multiqc:
    partition: iob_batch
    threads: 1
    mem: 10
    time: 00-01:00:00
    name: trimmed_multiqc

metaspades:
    partition: iob_highmem
    cpu: 68
    mem: 950
    time: 04-00:00:00
    name: assembly_metaspades

mitoz:
    partition: bik_p
    cpu: 4
    tasks: 1
    mem: 10
    time: 02-00:00:00
    name: mitoz

metaquast:
    partition: iob_batch
    cpu: 4
    tasks: 1
    mem: 15
    time: 03-00:00:00
    name: metaquast

busco:
    partition: iob_batch
    cpu: 8
    tasks: 1
    mem: 40
    time: 02-00:00:00
    name: busco

bwa_index:
    partition: bik_p
    cpu: 1
    ntasks: 1
    mem: 24
    time: 03-00:00:00
    name: index

pro_mapReads:
    partition: iob_p
    cpu: 24
    tasks: 1
    mem: 100
    time: 03-00:00:00
    name: map_reads

pro_metabat:
    partition: bik_p
    cpu: 4
    tasks: 1
    mem: 16
    time: 03-00:00:00
    name: pro_metabat

pro_completebin:
    partition: iob_batch
    cpu: 48
    tasks: 1
    mem: 480
    time: 07-00:00:00
    name: pro_completebin

pro_comebin:
    partition: iob_p
    cpu: 24
    tasks: 1
    mem: 240
    time: 07-00:00:00
    name: pro_comebin

contigtocomplete:
    partition: bik_p
    cpu: 1
    tasks: 1
    mem: 16
    time: 07-00:00:00
    name: contigtocomplete

contigtometabat:
    partition: bik_p
    cpu: 1
    tasks: 1
    mem: 16
    time: 07-00:00:00
    name: contigtometabat

contigtocomebin:
    partition: bik_p
    cpu: 1
    tasks: 1
    mem: 16
    time: 07-00:00:00
    name: contigtocomebin

pro_dastool:
    partition: bik_p
    cpu: 12
    tasks: 1
    mem: 5
    time: 03-00:00:00
    name: pro_dastool

flash:
    partition: bik_p
    cpu: 5
    tasks: 1
    mem: 10
    time: 01-00:00:00
    name: flash_reads

metaphlanDB:
    cpu: 5
    tasks: 1
    mem: 100
    time: 01-00:00:00
    name: taxonomy_DB

metaphlan:
    partition: bik_p
    cpu: 12
    tasks: 1
    mem: 50
    time: 03-00:00:00
    name: metaphlan

krakenDB:
    cpu: 24
    tasks: 1
    mem: 250
    time: 07-00:00:00
    name: krakenDB

kraken:
    cpu: 5
    tasks: 1
    mem: 100
    time: 03-00:00:00
    name: kraken

pro_gtdbtk:
    partition: iob_p
    cpu: 24
    tasks: 1
    mem: 150
    time: 03-00:00:00
    name: gtdbtk 

checkm:
    partition: bik_p
    cpu: 12
    tasks: 1
    mem: 25
    time: 00-12:00:00
    name: checkm

checkm_2:
    partition: iob_p
    cpu: 12
    tasks: 1
    mem: 150
    time: 00-12:00:00
    name: checkm

extract_bac:
    partition: iob_p
    cpu: 24
    tasks: 1
    mem: 120
    time: 00-12:00:00
    name: metaphlan
