__default__:
    system: slurm #check if system is defined below
    account: hmb_lab #requred
    partition: iob_p #required
    time: 00-12:00:00 # minutes
    mem: 10 # GB
    threads: 1
    nodes: 1
    cpu: 1
    tasks: 1
    name: snakejob
    mail_user: 'ad14556@uga.edu'
    mail_type: 'BEGIN,END,FAIL'

initial_fastqc:
    threads: 1
    mem: 10
    time: 00-01:00:00
    name: initial_fastqc

initial_multiqc:
    threads: 1
    mem: 10
    time: 00-01:00:00
    name: initial_multiqc

trimmomatic:
    threads: 2
    mem: 25
    time: 00-12:00:00
    name: trimmomatic

trimmed_fastqc:
    threads: 1
    mem: 10
    time: 00-01:00:00
    name: trimmed_fastqc

trimmed_multiqc:
    threads: 1
    mem: 10
    time: 00-01:00:00
    name: trimmed_multiqc

megahit:
    cpu: 24
    tasks: 1
    mem: 500
    time: 04-00:00:00
    name: assembly_megahit

metaquast:
    cpu: 4
    tasks: 1
    mem: 50
    time: 03-00:00:00
    name: metaquast

euk_mapReads:
    cpu: 10
    tasks: 1
    mem: 10
    time: 07-00:00:00
    name: map_reads

euk_metabat:
    cpu: 4
    tasks: 1
    mem: 10
    time: 07-00:00:00
    name: euk_metabat

euk_concoct:
    cpu: 4
    tasks: 1
    mem: 10
    time: 07-00:00:00
    name: euk_concoct

euk_dastool:
    cpu: 4
    tasks: 1
    mem: 15
    time: 07-00:00:00
    name: euk_dastool

busco:
    cpu: 4
    tasks: 1
    mem: 15
    time: 02-00:00:00
    name: busco

pro_mapReads:
    cpu: 4
    tasks: 1
    mem: 10
    time: 03-00:00:00
    name: map_reads

pro_metabat:
    cpu: 4
    tasks: 1
    mem: 10
    time: 03-00:00:00
    name: euk_metabat

pro_concoct:
    cpu: 4
    tasks: 1
    mem: 10
    time: 03-00:00:00
    name: euk_concoct

pro_dastool:
    cpu: 4
    tasks: 1
    mem: 15
    time: 03-00:00:00
    name: euk_dastool

flash:
    partition: bik_p
    cpu: 5
    tasks: 1
    mem: 2
    time: 01-00:00:00
    name: flash_reads

metaphlanDB:
    cpu: 5
    tasks: 1
    mem: 100
    time: 01-00:00:00
    name: taxonomy_DB

metaphlan:
    partition: bik_p
    cpu: 5
    tasks: 1
    mem: 50
    time: 03-00:00:00
    name: metaphlan

krakenDB:
    cpu: 24
    tasks: 1
    mem: 250
    time: 07-00:00:00
    name: krakenDB

kraken:
    cpu: 5
    tasks: 1
    mem: 100
    time: 03-00:00:00
    name: kraken
