####################
# edit config file #
####################

# make sure the path are:
# 1. absolute paths
# 2. directories
####################################
project_name: 'nematode_metagenomes'
input_path: '/scratch/ad14556/nemMetagenomes/00-raw-data/'
output_path: '/scratch/ad14556/nemMetagenomes/'
scratch_path: '/scratch/ad14556/nemMetagenomes/'


# quality control parameters
# look at the trimmomatic tutorial for more information
####################################
adapters: '/home/ad14556/snakemake-pipelines/metagenomicsPipeline/databases/NexteraPE-PE.fa'
phred_score: 'phred33'
mismatches: '2'
palindrome: '30'
simple_clip: '10'
leading_quality: '20'
trailing_quality: '20'
window_size: '4'
sliding_window_quality: '10'
minimum_seq_length: '25'
